server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gmps_auth
     username: root
     password: root
    # username: ${SPRING_DATASOURCE_USERNAME}
    # password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  # secret: ${JWT_SECRET}
  secret: mySecretKeyForGlobalMerchantPaymentPlatform2026
  expiration: 86400000

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
