server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/gmps_settlement
    username: root
    password: root

  application:
    name: settlement-service

  config:
    import: "optional:configserver:http://config-server:8888"


  kafka:
    bootstrap-servers: kafka:9092
